export const Users = [
  {
    _id: '66a3c8909622c8e2bdd2dbca',
    index: 0,
    guid: '33b1daf9-a7a9-4859-a563-4e386bd17a9d',
    isActive: false,
    balance: '$1,263.10',
    picture: 'http://placehold.it/32x32',
    age: 21,
    eyeColor: 'green',
    name: 'Hilda Lester',
    gender: 'female',
    company: 'BILLMED',
    email: 'hildalester@billmed.com',
    phone: '+1 (919) 489-3009',
    address: '797 Hillel Place, Blackgum, Oregon, 2915',
    about:
      'Pariatur ad non veniam est qui. Non dolore velit anim cupidatat commodo qui ex ea laboris deserunt anim Lorem. Sunt dolore cupidatat mollit deserunt et. Magna cupidatat culpa mollit nisi elit est. Nostrud amet et ea commodo.\r\n',
    registered: '2019-09-11T11:36:13 -03:00',
    latitude: -11.205951,
    longitude: 37.190797,
    tags: ['proident', 'in', 'ad', 'dolore', 'sit', 'et', 'excepteur'],
    friends: [
      {
        id: 0,
        name: 'Shelley Joyner',
      },
      {
        id: 1,
        name: 'Lizzie Hester',
      },
      {
        id: 2,
        name: 'Cardenas Burton',
      },
    ],
    greeting: 'Hello, Hilda Lester! You have 3 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '66a3c8909ac6af10b563a058',
    index: 1,
    guid: 'df84165a-73f0-454f-a90d-d62f9f2322b0',
    isActive: false,
    balance: '$2,757.65',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'blue',
    name: 'Rita Johnston',
    gender: 'female',
    company: 'MAINELAND',
    email: 'ritajohnston@maineland.com',
    phone: '+1 (809) 578-2289',
    address: '653 Church Avenue, Newry, North Carolina, 8515',
    about:
      'Sit aute nisi proident nulla ad. Mollit ad duis aute qui aliquip dolore dolore. Proident laboris ad ex consequat in consectetur fugiat nisi in voluptate.\r\n',
    registered: '2014-10-25T07:48:55 -03:00',
    latitude: 10.049945,
    longitude: -128.499068,
    tags: [
      'commodo',
      'enim',
      'excepteur',
      'reprehenderit',
      'irure',
      'quis',
      'nisi',
    ],
    friends: [
      {
        id: 0,
        name: 'Rowe Cantu',
      },
      {
        id: 1,
        name: 'Kemp Graves',
      },
      {
        id: 2,
        name: 'Lara Horton',
      },
    ],
    greeting: 'Hello, Rita Johnston! You have 7 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '66a3c8903b88d332107b397c',
    index: 2,
    guid: '8c8cd1cd-f14e-4890-980c-61cc6beec9a9',
    isActive: true,
    balance: '$1,739.48',
    picture: 'http://placehold.it/32x32',
    age: 26,
    eyeColor: 'green',
    name: 'Margarita Ayala',
    gender: 'female',
    company: 'DUFLEX',
    email: 'margaritaayala@duflex.com',
    phone: '+1 (979) 537-2008',
    address: '289 Doone Court, Cresaptown, Kansas, 7590',
    about:
      'Pariatur anim in et dolore excepteur nostrud proident aute mollit labore magna consequat exercitation laboris. Qui laborum consectetur sit est cupidatat qui culpa minim qui dolor Lorem magna. Incididunt aliquip velit et laborum sint cillum anim excepteur laboris est incididunt. Excepteur voluptate amet commodo cupidatat officia sit excepteur irure commodo excepteur. Proident amet ullamco exercitation sint est.\r\n',
    registered: '2020-05-31T10:18:04 -03:00',
    latitude: 74.364053,
    longitude: 63.11027,
    tags: [
      'commodo',
      'aute',
      'enim',
      'duis',
      'consectetur',
      'deserunt',
      'nisi',
    ],
    friends: [
      {
        id: 0,
        name: 'Walls Langley',
      },
      {
        id: 1,
        name: 'Pauline Combs',
      },
      {
        id: 2,
        name: 'Melinda Adams',
      },
    ],
    greeting: 'Hello, Margarita Ayala! You have 9 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '66a3c890dbe32f84df492f5d',
    index: 3,
    guid: '6f28f2f8-c29d-47a7-881f-e056f5c1e7a0',
    isActive: false,
    balance: '$1,849.53',
    picture: 'http://placehold.it/32x32',
    age: 40,
    eyeColor: 'green',
    name: 'Oneill Grimes',
    gender: 'male',
    company: 'XEREX',
    email: 'oneillgrimes@xerex.com',
    phone: '+1 (988) 465-3485',
    address: '175 Thornton Street, Bagtown, Maine, 7056',
    about:
      'Eu excepteur amet aliquip cupidatat aliqua elit voluptate officia id consectetur velit excepteur eiusmod dolor. Aute sint deserunt commodo pariatur amet amet magna cillum Lorem cupidatat laboris. Reprehenderit dolor aliquip dolore nulla elit proident mollit aute commodo id magna sunt. Commodo aliquip proident minim sunt enim proident.\r\n',
    registered: '2016-02-11T07:03:15 -02:00',
    latitude: 0.49579,
    longitude: -32.856939,
    tags: ['ullamco', 'nisi', 'id', 'nisi', 'ad', 'labore', 'aute'],
    friends: [
      {
        id: 0,
        name: 'Charity Benjamin',
      },
      {
        id: 1,
        name: 'Ofelia Gomez',
      },
      {
        id: 2,
        name: 'Tara Reed',
      },
    ],
    greeting: 'Hello, Oneill Grimes! You have 6 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '66a3c8905e4552b504d0fe33',
    index: 4,
    guid: '6c874585-ba20-43e6-a4e8-42f00ac7e863',
    isActive: true,
    balance: '$1,441.42',
    picture: 'http://placehold.it/32x32',
    age: 20,
    eyeColor: 'brown',
    name: 'Farrell Phillips',
    gender: 'male',
    company: 'MINGA',
    email: 'farrellphillips@minga.com',
    phone: '+1 (884) 441-3134',
    address: '588 Croton Loop, Valmy, Alabama, 9959',
    about:
      'Tempor laborum magna veniam aliquip. Et culpa elit duis commodo. Cupidatat laborum proident cupidatat qui sint culpa est irure aliqua. Ea sunt exercitation duis cillum quis esse. Proident id sit sint et est consequat occaecat.\r\n',
    registered: '2023-03-22T04:19:14 -02:00',
    latitude: 10.806382,
    longitude: -76.729757,
    tags: ['tempor', 'dolor', 'sit', 'minim', 'non', 'magna', 'eiusmod'],
    friends: [
      {
        id: 0,
        name: 'Buck Chapman',
      },
      {
        id: 1,
        name: 'Pearl Owen',
      },
      {
        id: 2,
        name: 'Patricia Carson',
      },
    ],
    greeting: 'Hello, Farrell Phillips! You have 1 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '66a3c890655e1663716944bf',
    index: 5,
    guid: '78301cf2-dd0e-481d-8fe6-f65e00658557',
    isActive: false,
    balance: '$3,561.72',
    picture: 'http://placehold.it/32x32',
    age: 28,
    eyeColor: 'green',
    name: 'Mary Rollins',
    gender: 'female',
    company: 'KINETICA',
    email: 'maryrollins@kinetica.com',
    phone: '+1 (808) 495-2004',
    address: '100 Ivan Court, Troy, Colorado, 2022',
    about:
      'Eu quis nisi Lorem sit. Sint amet occaecat officia ad cupidatat quis velit ut magna. Adipisicing reprehenderit ipsum laboris incididunt adipisicing deserunt ullamco ea mollit deserunt non occaecat esse laborum. Est elit dolor do do velit laboris fugiat sunt minim nisi amet sunt enim. Dolore excepteur duis minim ut consectetur.\r\n',
    registered: '2017-03-07T01:42:50 -02:00',
    latitude: 35.116572,
    longitude: -165.864332,
    tags: [
      'ipsum',
      'excepteur',
      'non',
      'occaecat',
      'exercitation',
      'labore',
      'consectetur',
    ],
    friends: [
      {
        id: 0,
        name: 'Russell Marshall',
      },
      {
        id: 1,
        name: 'Walsh Figueroa',
      },
      {
        id: 2,
        name: 'Angelita Robinson',
      },
    ],
    greeting: 'Hello, Mary Rollins! You have 4 unread messages.',
    favoriteFruit: 'apple',
  },
];
